image: alpine:latest

pages:
  stage: deploy
  before_script:
  - apk update
  - apk add discount
  script:
  - mkdir out
  - cp -r inc/* out/
  - for PART in $( find src -type f -name '*.part' ! -empty ); do HTML="out${PART#src}"; HTML="${HTML%.part}"; mkdir -p $( dirname $HTML ); cat prt/header.html.part $PART prt/footer.html.part > $HTML; done
  - for MARK in $( find src -type f -name '*.md' ! -empty ); do HTML="out${MARK#src}"; HTML="${HTML%.md}.html"; mkdir -p $( dirname $HTML ); cat prt/header.html.part > $HTML; sed 's/^#/##/g' $MARK | markdown >> $HTML; cat prt/footer.html.part >> $HTML; done
  - for FILE in $( find src -type f ! -name '*.md' ! -name '*.part' ! -empty ); do DEST="out${FILE#src}"; mkdir -p $( dirname $DEST ); cp $FILE $DEST; done
  after_script:
  - mv out public
  - cp public/h.html public/index.html
  artifacts:
    paths:
    - public
