image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir out
  - cp -r inc/* out/
  - for PART in $( find src -type f -name *.part ! -empty ); do HTML="out${PART#src}"; HTML="${HTML%.part}"; mkdir -p $( dirname $HTML ); cat prt/header.html.part $PART prt/footer.html.part > $HTML; done
  - for FILE in $( find src -type f ! -name *.part ! -empty ); do mkdir -p $( dirname "out${FILE#src}" ); cp $FILE "out${HTML#src}"; done
  after_script:
  - mv out public
  - cp public/h.html public/index.html
  artifacts:
    paths:
    - public
